// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	Alias                string         `json:"alias"`
	Balance              string         `json:"balance"`
	LastMovementType     sql.NullString `json:"last_movement_type"`
	LastDeposit          sql.NullTime   `json:"last_deposit"`
	LastDepositAmount    sql.NullString `json:"last_deposit_amount"`
	LastTransfer         sql.NullTime   `json:"last_transfer"`
	LastTransferAccount  sql.NullString `json:"last_transfer_account"`
	LastTransferAmount   sql.NullString `json:"last_transfer_amount"`
	LastWhidrawal        sql.NullTime   `json:"last_whidrawal"`
	LastWhitdrawalAmount sql.NullString `json:"last_whitdrawal_amount"`
}

type User struct {
	Alias       string       `json:"alias"`
	Name        string       `json:"name"`
	Email       string       `json:"email"`
	Password    string       `json:"password"`
	SignedUp    time.Time    `json:"signed_up"`
	LastSession sql.NullTime `json:"last_session"`
}
